version: '3.9'
services:
  db:
    container_name: db
    # restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - calculator-network
#    networks:
#          calculator-network:
#            - ipv4_address: 172.30.0.2
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - calculator-network
#        calculator-network:
#          - ipv4_address: 172.30.0.3
#    networks:
#      calculator-network:
#        - ipv4_address: 172.30.0.2
#networks:
#  calculator-network:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.30.0.0/24"

networks:
  calculator-network:
    driver: bridge